services:
  flask-app:
    build: ./flask-app  # Path to the directory with Dockerfile
    ports:
      - "5000:5000"     # Exposing the Flask app on port 5000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - flask-redis-network

  redis:
    image: "redis:alpine"  # Using Redis image from DockerHub
    ports:
      - "6379:6379"        # Exposing Redis on port 6379
    networks:
      - flask-redis-network
  worker:
    build: ./worker  # Path to the worker directory
    depends_on:
      - redis
    networks:
      - flask-redis-network
networks:
  flask-redis-network:
    driver: bridge
