---
# webserver/tasks/main.yml

- name: Install Apache
  apt:
    name: apache2
    state: present
  become: yes  # Use sudo to run the command as a superuser

- name: Start Apache service
  service:
    name: apache2
    state: started
    enabled: yes
  become: yes  # Use sudo to run the command as a superuser

- name: Deploy index.html
  copy:
    src: files/index.html
    dest: /var/www/html/index.html
    owner: www-data  # Set the owner to the web server user
    group: www-data  # Set the group to the web server group
    mode: '0644'     # Set permissions to read/write for owner, and read for others
  become: yes  # Use sudo to run the command as a superuser
