name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to docker
      run: docker login -u $env.DOCKER_USER -p $secret.DOCKER_PASS
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag serbentas/ca-test:latest
    - name: Push image
      run: docker push serbentas/ca-test:latest

