name: Terraform plan / apply

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch: 
    inputs:
      environment:
        type: choice
        description: Envornment
        options: 
        - dev
        - stage
        - prod
        - all
        default: test

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Terraform plan 
      run: |
        cd ca-workrepo\27
        if [[ "${{ github.event.inputs.environment }}" == "all" ]]; then
            terraform plan
        else
            terraform plan --target=module.${{ github.event.inputs.environment }}
        fi
    - name: Terraform apply
      run: |
        cd ca-workrepo\27
        if [[ "${{ github.event.inputs.environment }}" == "all" ]]; then
            terraform apply --auto-apprrove
        else
            terraform apply-autoapprove --target=module.${{ github.event.inputs.environment }}
        fi