name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 
    inputs:
      environment:
        type: choice
        description: Envornment
        options: 
        - test
        - stage
        - prod
        - all
        default: test
env:
  DOCKER_USER: serbentas
  DOCKER_CONTEXTDIR: "21/example/"
jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Terraform plan 
      run: |
        if [[ "${{ github.event.inputs.environment }}" == "all" ]]; then
            terraform plan
        else
            terraform plan --target=module.${{ github.event.inputs.environment }}
        fi
    - name: Terraform apply
      run: |
        if [[ "${{ github.event.inputs.environment }}" == "all" ]]; then
            terraform apply --auto-apprrove
        else
            terraform apply-autoapprove --target=module.${{ github.event.inputs.environment }}
        fi