name: Terraform plan / apply

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch: 
    inputs:
      environment:
        type: choice
        description: Envornment
        options: 
        - dev
        - stage
        - prod
        - all
        default: test
  

jobs:

  build:
    env: 
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Terraform plan 
      run: |
        cd 27
        terraform init
        if [[ "${{ github.event.inputs.environment }}" == "all" ]]; then
            terraform plan
        else
            terraform plan --target=module.${{ github.event.inputs.environment }}
        fi
    - name: Terraform apply
      run: |
        cd 27
        if [[ "${{ github.event.inputs.environment }}" == "all" ]]; then
            terraform apply --auto-apprrove
        else
            terraform apply-autoapprove --target=module.${{ github.event.inputs.environment }}
        fi